{
 "title": "IGA Dev & Staging - Server Monitoring",
 "tags": [
  "iga",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Node Exporter Monitoring (RHEL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Utilization - Node Exporter (RHEL Servers)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{job=\"node\", mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node\"}[5m]))))",
       "legendFormat": "CPU"
      },
      {
       "expr": "1 - ((node_memory_MemAvailable_bytes{job=\"node\"}) / (node_memory_MemTotal_bytes{job=\"node\"}))",
       "legendFormat": "Memory"
      },
      {
       "expr": "1 - ((node_filesystem_avail_bytes{job=\"node\", fstype!=\"tmpfs\", mountpoint=\"/\"}) / (node_filesystem_size_bytes{job=\"node\", fstype!=\"tmpfs\", mountpoint=\"/\"}))",
       "legendFormat": "Storage"
      }
     ]
    }
   ]
  },
  {
   "title": "Windows Exporter Monitoring (Windows)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "panels": [
    {
     "title": "Utilization - Windows Exporter (Windows Servers)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(windows_cpu_time_total{job=\"winex\", mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{job=\"winex\"}[5m]))))",
       "legendFormat": "CPU"
      },
      {
       "expr": "1 - ((windows_memory_available_bytes{job=\"winex\"}) / (windows_cs_physical_memory_bytes{job=\"winex\"}))",
       "legendFormat": "Memory"
      },
      {
       "expr": "1 - ((windows_logical_disk_free_bytes{job=\"winex\", volume=\"C:\"}) / (windows_logical_disk_size_bytes{job=\"winex\", volume=\"C:\"}))",
       "legendFormat": "Storage"
      }
     ]
    }
   ]
  },
  {
   "title": "Blackbox Exporter Monitoring (Service Availability)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "panels": [
    {
     "title": "Service Availability - Blackbox Exporter",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "min_over_time(probe_success{job=\"blackbox\"}[5m])",
       "legendFormat": "Status"
      }
     ]
    }
   ]
  }
 ]
}